import {NgModule} from '@angular/core';
import {
	MatButtonModule,
	MatCardModule,
	MatDialogModule,
	MatIconModule,
	MatInputModule,
	MatListModule,
	MatMenuModule,
	MatProgressSpinnerModule,
	MatSelectModule,
	MatButtonToggleModule,
	MatSlideToggleModule,
	MatSnackBarModule,
	MatToolbarModule,
	MatTabsModule,
	MatSidenavModule,
	MatTooltipModule,
	MatRippleModule,
	MatRadioModule,
	MatGridListModule,
	MatDatepickerModule,
	MatNativeDateModule, MatSliderModule, MatAutocompleteModule, MatTableModule
} from '@angular/material';
import {
	CovalentCommonModule, CovalentDataTableModule, CovalentDialogsModule,
	CovalentExpansionPanelModule,
	CovalentLayoutModule, CovalentLoadingModule,
	CovalentMediaModule, CovalentMenuModule, CovalentMessageModule, CovalentNotificationsModule, CovalentPagingModule, CovalentSearchModule,
	CovalentStepsModule
} from '@covalent/core';


@NgModule({
	imports: [
		/** Material Modules */
		MatDialogModule,
		MatButtonModule,
		MatListModule,
		MatIconModule,
		MatCardModule,
		MatMenuModule,
		MatInputModule,
		MatSelectModule,
		MatButtonToggleModule,
		MatSlideToggleModule,
		MatProgressSpinnerModule,
		MatDialogModule,
		MatSnackBarModule,
		MatToolbarModule,
		MatTabsModule,
		MatSidenavModule,
		MatTooltipModule,
		MatRippleModule,
		MatRadioModule,
		MatGridListModule,
		MatDatepickerModule,
		MatNativeDateModule,
		MatSliderModule,
		MatAutocompleteModule,
		MatTableModule,
		/** Covalent Modules */
		CovalentCommonModule,
		CovalentLayoutModule,
		CovalentMediaModule,
		CovalentExpansionPanelModule,
		CovalentStepsModule,
		CovalentDialogsModule,
		CovalentLoadingModule,
		CovalentSearchModule,
		CovalentPagingModule,
		CovalentNotificationsModule,
		CovalentMenuModule,
		CovalentDataTableModule,
		CovalentMessageModule,
	],
	exports: [
		/** Material Modules */
		MatDialogModule,
		MatButtonModule,
		MatListModule,
		MatIconModule,
		MatCardModule,
		MatMenuModule,
		MatInputModule,
		MatSelectModule,
		MatButtonToggleModule,
		MatSlideToggleModule,
		MatProgressSpinnerModule,
		MatDialogModule,
		MatSnackBarModule,
		MatToolbarModule,
		MatTabsModule,
		MatSidenavModule,
		MatTooltipModule,
		MatRippleModule,
		MatRadioModule,
		MatGridListModule,
		MatDatepickerModule,
		MatNativeDateModule,
		MatSliderModule,
		MatAutocompleteModule,
		MatTableModule,
		/** Covalent Modules */
		CovalentCommonModule,
		CovalentLayoutModule,
		CovalentMediaModule,
		CovalentExpansionPanelModule,
		CovalentStepsModule,
		CovalentDialogsModule,
		CovalentLoadingModule,
		CovalentSearchModule,
		CovalentPagingModule,
		CovalentNotificationsModule,
		CovalentMenuModule,
		CovalentDataTableModule,
		CovalentMessageModule,
	]
})
export class AngularMaterialModule {
}
